# Generated by Django 4.1.7 on 2023-03-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='faculty',
            field=models.CharField(default='bsccsit', max_length=50),
            preserve_default=False,
        ),
    ]
