# Generated by Django 4.1.7 on 2023-05-03 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_alter_account_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="phone_number",
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"groups__name": "student"},
                        related_name="students_present",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
