# Generated by Django 4.1.7 on 2023-03-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_remove_course_notice_remove_course_semester_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Faculty',
        ),
    ]
