# Generated by Django 4.1.7 on 2023-04-10 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("faculty", "0004_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="faculty.faculty",
                to_field="name",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
