# Generated by Django 4.1.7 on 2023-04-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faculty", "0007_alter_subject_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="notice",
            field=models.CharField(default="Test", max_length=250),
            preserve_default=False,
        ),
    ]
