# Generated by Django 4.1.7 on 2023-04-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faculty", "0008_subject_notice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="notice",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
