# Generated by Django 4.1.7 on 2023-04-21 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("faculty", "0010_assignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="faculty.subject",
                to_field="name",
            ),
        ),
    ]
