# Generated by Django 4.1.7 on 2023-04-21 02:23

from django.db import migrations, models
import faculty.models


class Migration(migrations.Migration):
    dependencies = [
        ("faculty", "0011_alter_assignment_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="assignment_file",
            field=models.FileField(upload_to=faculty.models.file_name_generator),
        ),
    ]
