# Generated by Django 4.1.7 on 2023-04-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faculty", "0012_alter_assignment_assignment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="title",
            field=models.CharField(max_length=60),
        ),
    ]
