# Generated by Django 4.1.7 on 2023-04-22 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("faculty", "0014_assignment_submitted_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="submitted_by",
        ),
        migrations.AddField(
            model_name="assignment",
            name="submitted_by",
            field=models.ManyToManyField(
                limit_choices_to={"groups__name": "student"},
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
