# Generated by Django 4.1.7 on 2023-04-22 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("faculty", "0015_remove_assignment_submitted_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="submitted_by",
        ),
    ]
