# Generated by Django 4.1.7 on 2023-04-22 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("faculty", "0016_remove_assignment_submitted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="submitted_by",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"groups__name": "teacher"},
                related_name="assignment_submitted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
