# Generated by Django 4.1.7 on 2023-05-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faculty", "0017_assignment_submitted_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="deadline",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
